"""added_review_id_2_review_doc

Revision ID: 087542d4c647
Revises: 72ca98761503
Create Date: 2022-03-15 11:13:18.418545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087542d4c647'
down_revision = '72ca98761503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
