"""datetime_2_ffdwdf

Revision ID: 0c418a34fcb4
Revises: dea7ad42e66a
Create Date: 2022-03-28 11:49:58.140066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c418a34fcb4'
down_revision = 'dea7ad42e66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'date_of_birth')
    # ### end Alembic commands ###
