"""user_phone

Revision ID: 19fdab1344ec
Revises: 7d01a7e66b51
Create Date: 2022-02-25 15:17:52.680629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fdab1344ec'
down_revision = '7d01a7e66b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customers', ['id'])
    op.create_unique_constraint(None, 'payments', ['id'])
    op.create_unique_constraint(None, 'price_list', ['id'])
    op.create_unique_constraint(None, 'review', ['id'])
    op.create_unique_constraint(None, 'review_document', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_document', type_='unique')
    op.drop_constraint(None, 'review', type_='unique')
    op.drop_constraint(None, 'price_list', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    # ### end Alembic commands ###
