"""table_review_added_4_fields

Revision ID: 22c3c521362f
Revises: 5ad24c0ea264
Create Date: 2022-03-07 09:58:00.540784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22c3c521362f'
down_revision = '5ad24c0ea264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.add_column('review', sa.Column('date_of_creation_payment', sa.DateTime(), nullable=True))
    op.add_column('review', sa.Column('finance_id', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('paid', sa.Boolean(), nullable=True))
    op.add_column('review', sa.Column('payment_made', sa.Enum('cash', 'card', 'cash_card', name='pays'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'payment_made')
    op.drop_column('review', 'paid')
    op.drop_column('review', 'finance_id')
    op.drop_column('review', 'date_of_creation_payment')
    op.create_table('payments',
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customers_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_of_service', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('payment_made', postgresql.ENUM('cash', 'card', 'cash_card', name='pays'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_of_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customers_id'], ['customers.id'], name='payments_customers_id_fkey'),
    sa.ForeignKeyConstraint(['finance_id'], ['review.id'], name='payments_finance_id_fkey'),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_list.id'], name='payments_price_list_id_fkey'),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name='payments_review_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='payments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    sa.UniqueConstraint('id', name='payments_id_key')
    )
    # ### end Alembic commands ###
