"""datetime_2_ffdwdf

Revision ID: 29c67cc87c7c
Revises: 71f5f03e7c82
Create Date: 2022-03-28 11:43:38.873915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c67cc87c7c'
down_revision = '71f5f03e7c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'date_of_birth')
    # ### end Alembic commands ###
