"""added_hashed_password

Revision ID: 32d40205fff2
Revises: 087542d4c647
Create Date: 2022-03-18 12:15:37.599914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d40205fff2'
down_revision = '087542d4c647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_document', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'review_document', 'review', ['review_id'], ['id'])
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hashed_password')
    op.drop_constraint(None, 'review_document', type_='foreignkey')
    op.alter_column('review_document', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
