"""added_jmbg_deleted

Revision ID: 33d57648882a
Revises: 3c0ea3f6cd32
Create Date: 2022-03-10 11:04:01.802000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d57648882a'
down_revision = '3c0ea3f6cd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('jmbg', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['jmbg'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'jmbg')
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###
