"""izbacen jmbg iz Usera

Revision ID: 34f5c2864c1b
Revises: ae5f5cb7f593
Create Date: 2022-03-03 10:29:04.042779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f5c2864c1b'
down_revision = 'ae5f5cb7f593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'jmbg',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('customers_jmbg_key', 'customers', type_='unique')
    op.drop_constraint('user_jmbg_key', 'user', type_='unique')
    op.drop_column('user', 'jmbg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('jmbg', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_jmbg_key', 'user', ['jmbg'])
    op.create_unique_constraint('customers_jmbg_key', 'customers', ['jmbg'])
    op.alter_column('customers', 'jmbg',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
