"""added_session_id_jmbg_str

Revision ID: 3c0ea3f6cd32
Revises: 5dfe9fbb4665
Create Date: 2022-03-09 13:30:35.544462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0ea3f6cd32'
down_revision = '5dfe9fbb4665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('company_pib', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('jmbg', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'jmbg')
    op.drop_column('customers', 'company_pib')
    # ### end Alembic commands ###
