"""added_to_delete

Revision ID: 5dfe9fbb4665
Revises: 5945708da0c8
Create Date: 2022-03-09 13:27:57.328991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfe9fbb4665'
down_revision = '5945708da0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'jmbg')
    op.drop_column('customers', 'company_pib')
    op.add_column('user', sa.Column('session_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'session_id')
    op.add_column('customers', sa.Column('company_pib', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('jmbg', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
