"""user_phone_rem

Revision ID: 6ad2fc24f1f8
Revises: 19fdab1344ec
Create Date: 2022-02-25 15:19:22.270347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad2fc24f1f8'
down_revision = '19fdab1344ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_phone_key', 'customers', type_='unique')
    op.drop_column('customers', 'phone')
    op.drop_constraint('user_phone_key', 'user', type_='unique')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_phone_key', 'user', ['phone'])
    op.add_column('customers', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('customers_phone_key', 'customers', ['phone'])
    # ### end Alembic commands ###
