"""datetime_2_fdssd

Revision ID: 71f5f03e7c82
Revises: f1fda4d52e24
Create Date: 2022-03-28 11:40:06.924962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f5f03e7c82'
down_revision = 'f1fda4d52e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_list', sa.Column('date_of_end', sa.DateTime(), nullable=True))
    op.add_column('review', sa.Column('date_of_creation_payment', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'date_of_creation_payment')
    op.drop_column('price_list', 'date_of_end')
    # ### end Alembic commands ###
