"""added_review_id_2_review_doc

Revision ID: 72ca98761503
Revises: 33d57648882a
Create Date: 2022-03-15 11:06:15.075352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72ca98761503'
down_revision = '33d57648882a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('review_document', sa.Column('review_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_document', 'review_id')
    op.alter_column('customers', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
