"""added_hashed_password(150)

Revision ID: 9c1449370598
Revises: 32d40205fff2
Create Date: 2022-03-18 12:46:32.039162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1449370598'
down_revision = '32d40205fff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
