"""izbacen surname ostavljen samo name

Revision ID: ae5f5cb7f593
Revises: f8bda33419d2
Create Date: 2022-03-03 10:19:23.771978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5f5cb7f593'
down_revision = 'f8bda33419d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'surname')
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('surname', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
