"""t

Revision ID: b3b573f46568
Revises: 22c3c521362f
Create Date: 2022-03-07 14:30:43.112327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b573f46568'
down_revision = '22c3c521362f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'finance_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('finance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
