"""datetime_2_date

Revision ID: b3ee7d1a3f0a
Revises: 9c1449370598
Create Date: 2022-03-28 10:28:47.533582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ee7d1a3f0a'
down_revision = '9c1449370598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
