"""user_phone_add

Revision ID: da4d5a5b5f75
Revises: 6ad2fc24f1f8
Create Date: 2022-02-25 15:20:18.941985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4d5a5b5f75'
down_revision = '6ad2fc24f1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'customers', ['phone'])
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
