"""finance_id_add

Revision ID: df417257ae2c
Revises: 34f5c2864c1b
Create Date: 2022-03-03 15:32:10.305175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df417257ae2c'
down_revision = '34f5c2864c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('finance_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payments', 'review', ['finance_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'finance_id')
    # ### end Alembic commands ###
