"""initial

Revision ID: ee458ec34c78
Revises: 
Create Date: 2022-02-23 14:36:38.461668

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ee458ec34c78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('role', sa.Enum('admin', 'doctor', 'finance', name='role'), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('surname', sa.String(length=255), nullable=False),
                    sa.Column('jmbg', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('address', sa.String(length=255), nullable=True),
                    sa.Column('phone', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('date_of_creation', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('id'),
                    sa.UniqueConstraint('jmbg'),
                    sa.UniqueConstraint('phone')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
