"""price_list_date_of_end_add

Revision ID: f8bda33419d2
Revises: da4d5a5b5f75
Create Date: 2022-03-01 10:55:34.313954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bda33419d2'
down_revision = 'da4d5a5b5f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_list', sa.Column('date_of_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_list', 'date_of_end')
    # ### end Alembic commands ###
